matchBlocks=minecraft:stone minecraft:cobblestone
method=ctm_compact
connect=list
connectBlocks=minecraft:water minecraft:flowing_water
renderLayer=5
renderPass=translucent
tiles=none mossy_stone_full mossy_stone_vert mossy_stone_horiz mossy_stone_corners
weight=50
