matchBlocks=minecraft:stone minecraft:cobblestone
method=ctm_compact
connect=list
connectBlocks=minecraft:air
abuttingBlocks=minecraft:lava minecraft:flowing_lava
renderLayer=1
renderPass=solid
tiles=stone2air_empty stone2air_full stone2air_vert stone2air_horiz stone2air_corners
weight=50
