matchBlocks=minecraft:stone minecraft:cobblestone
method=ctm_compact
connect=rlist
connectBlocks=minecraft:lava minecraft:flowing_lava
abuttingBlocks=minecraft:air
renderLayer=6
renderPass=solid
tiles=stone2lava_empty stone2lava_full stone2lava_vert stone2lava_horiz stone2lava_corners
weight=100
