matchBlocks=minecraft:cobblestone minecraft:stone minecraft:sand
method=random
abuttingBlocks=minecraft:water minecraft:flowing_water
renderLayer=2
renderPass=translucent
tiles=none mossystone_face_full
weight=2


SCi4