matchBlocks=minecraft:stone minecraft:cobblestone minecraft:gravel minecraft:dirt minecraft:grass minecraft:sand
method=fixed
abuttingBlocks=minecraft:ice
renderLayer=5
renderPass=translucent
tiles=frostedface
weight=50
