matchBlocks=minecraft:dirt minecraft:gravel minecraft:cobblestone minecraft:stone
method=ctm_compact
connect=rlist
connectBlocks=minecraft:sand
abuttingBlocks=minecraft:air
renderLayer=3
renderPass=translucent
tiles=sandy_empty sandy_full sandy_vert sandy_horiz sandy_corners
weight=10
