matchBlocks=minecraft:glass_pane
method=ctm_compact
connectBlocks=minecraft:planks
connectMetadata=0
renderLayer=7
renderPass=translucent
tiles=paneclips_full paneclips_full paneclips_sides paneclips_vert none
weight=50