matchBlocks=minecraft:stone minecraft:cobblestone minecraft:gravel minecraft:dirt minecraft:grass minecraft:sand
method=ctm_compact
connect=rlist
connectBlocks=minecraft:ice
renderLayer=6
renderPass=translucent
tiles=frostedsides_empty frostedsides_full frostedsides_vert frostedsides_horiz frostedsides_corners
weight=70
